// Copyright (c) 2026 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/services/snapshot/v1/snapshot.proto

package snapshot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_services_snapshot_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_snapshot_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_services_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StatusRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *StatusRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	RemoteReady   bool                   `protobuf:"varint,6,opt,name=remote_ready,json=remoteReady,proto3" json:"remote_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_services_snapshot_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_snapshot_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_services_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StatusResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *StatusResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetRemoteReady() bool {
	if x != nil {
		return x.RemoteReady
	}
	return false
}

var File_api_services_snapshot_v1_snapshot_proto protoreflect.FileDescriptor

const file_api_services_snapshot_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"'api/services/snapshot/v1/snapshot.proto\x12\x1ccubelet.services.snapshot.v1\"i\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\"\xbd\x01\n" +
	"\x0eStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12!\n" +
	"\fremote_ready\x18\x06 \x01(\bR\vremoteReady2o\n" +
	"\bSnapshot\x12c\n" +
	"\x06Status\x12+.cubelet.services.snapshot.v1.StatusRequest\x1a,.cubelet.services.snapshot.v1.StatusResponseBOZMgithub.com/tencentcloud/CubeSandbox/Cubelet/api/services/snapshot/v1;snapshotb\x06proto3"

var (
	file_api_services_snapshot_v1_snapshot_proto_rawDescOnce sync.Once
	file_api_services_snapshot_v1_snapshot_proto_rawDescData []byte
)

func file_api_services_snapshot_v1_snapshot_proto_rawDescGZIP() []byte {
	file_api_services_snapshot_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_api_services_snapshot_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_snapshot_v1_snapshot_proto_rawDesc), len(file_api_services_snapshot_v1_snapshot_proto_rawDesc)))
	})
	return file_api_services_snapshot_v1_snapshot_proto_rawDescData
}

var file_api_services_snapshot_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_services_snapshot_v1_snapshot_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: cubelet.services.snapshot.v1.StatusRequest
	(*StatusResponse)(nil), // 1: cubelet.services.snapshot.v1.StatusResponse
}
var file_api_services_snapshot_v1_snapshot_proto_depIdxs = []int32{
	0, // 0: cubelet.services.snapshot.v1.Snapshot.Status:input_type -> cubelet.services.snapshot.v1.StatusRequest
	1, // 1: cubelet.services.snapshot.v1.Snapshot.Status:output_type -> cubelet.services.snapshot.v1.StatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_services_snapshot_v1_snapshot_proto_init() }
func file_api_services_snapshot_v1_snapshot_proto_init() {
	if File_api_services_snapshot_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_snapshot_v1_snapshot_proto_rawDesc), len(file_api_services_snapshot_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_services_snapshot_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_api_services_snapshot_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_api_services_snapshot_v1_snapshot_proto_msgTypes,
	}.Build()
	File_api_services_snapshot_v1_snapshot_proto = out.File
	file_api_services_snapshot_v1_snapshot_proto_goTypes = nil
	file_api_services_snapshot_v1_snapshot_proto_depIdxs = nil
}
