// Copyright (c) 2026 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api/services/snapshot/v1/snapshot.proto

package snapshot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Snapshot_Status_FullMethodName      = "/cubelet.services.snapshot.v1.Snapshot/Status"
	Snapshot_BatchStatus_FullMethodName = "/cubelet.services.snapshot.v1.Snapshot/BatchStatus"
)

// SnapshotClient is the client API for Snapshot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Snapshot is Cubelet's snapshot control-plane service.
// Status is the upload query CubeMaster polls for remote_status.
// State comes from cubecow_get_volume_info export_status
// (NONE→pending, INPROGRESS→running, DONE→ready).
// BatchStatus is for ops tooling (e.g. cubemastercli --s3 list) to query
// many snapshot packages on one node in a single RPC.
type SnapshotClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	BatchStatus(ctx context.Context, in *BatchStatusRequest, opts ...grpc.CallOption) (*BatchStatusResponse, error)
}

type snapshotClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotClient(cc grpc.ClientConnInterface) SnapshotClient {
	return &snapshotClient{cc}
}

func (c *snapshotClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Snapshot_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotClient) BatchStatus(ctx context.Context, in *BatchStatusRequest, opts ...grpc.CallOption) (*BatchStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchStatusResponse)
	err := c.cc.Invoke(ctx, Snapshot_BatchStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotServer is the server API for Snapshot service.
// All implementations must embed UnimplementedSnapshotServer
// for forward compatibility.
//
// Snapshot is Cubelet's snapshot control-plane service.
// Status is the upload query CubeMaster polls for remote_status.
// State comes from cubecow_get_volume_info export_status
// (NONE→pending, INPROGRESS→running, DONE→ready).
// BatchStatus is for ops tooling (e.g. cubemastercli --s3 list) to query
// many snapshot packages on one node in a single RPC.
type SnapshotServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	BatchStatus(context.Context, *BatchStatusRequest) (*BatchStatusResponse, error)
	mustEmbedUnimplementedSnapshotServer()
}

// UnimplementedSnapshotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotServer struct{}

func (UnimplementedSnapshotServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedSnapshotServer) BatchStatus(context.Context, *BatchStatusRequest) (*BatchStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchStatus not implemented")
}
func (UnimplementedSnapshotServer) mustEmbedUnimplementedSnapshotServer() {}
func (UnimplementedSnapshotServer) testEmbeddedByValue()                  {}

// UnsafeSnapshotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotServer will
// result in compilation errors.
type UnsafeSnapshotServer interface {
	mustEmbedUnimplementedSnapshotServer()
}

func RegisterSnapshotServer(s grpc.ServiceRegistrar, srv SnapshotServer) {
	// If the following call panics, it indicates UnimplementedSnapshotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Snapshot_ServiceDesc, srv)
}

func _Snapshot_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Snapshot_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snapshot_BatchStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServer).BatchStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Snapshot_BatchStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServer).BatchStatus(ctx, req.(*BatchStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Snapshot_ServiceDesc is the grpc.ServiceDesc for Snapshot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Snapshot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.snapshot.v1.Snapshot",
	HandlerType: (*SnapshotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Snapshot_Status_Handler,
		},
		{
			MethodName: "BatchStatus",
			Handler:    _Snapshot_BatchStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/snapshot/v1/snapshot.proto",
}
